### PR TITLE
Hotfix/timeout

### PR DESCRIPTION
**Pull request by mrasu**
### Purpose/goal of PR (Issue #)
Add timeout for file_get_content

### Comments
Because this PR contains https://github.com/WOVNio/WOVN.php/pull/21, this should be merged after the PR.

### CODE REVIEW

**Comment by suplo** [comment]
could you please rebase to #21 branch?

**Comment by mrasu** [comment]
I will do after the PR is merged

**Comment by a-bougouin** [comment]
Update the branch please

**Comment by mrasu** [comment]
updated!

**Comment by a-bougouin** [comment]
I guess you can merge then

**Pull request merged**
